import type { Difficulty, Problem, Source } from "./types";
import { COVER_IMAGES } from "./domain-images";

type Template = {
  headline: string;
  description: string;
  domain: string;
  difficulty: Difficulty;
  context: string;
  tried_before: string;
  tags: string[];
  time_estimate: string;
};

const TEMPLATES: Template[] = [
  {
    headline: "Therapists spend 40% of session time on notes, not patients",
    description: "Mental health professionals burn out on EHR paperwork designed for billing, not care delivery.",
    domain: "Health",
    difficulty: "Medium",
    context: "EHR systems were designed for insurance billing — not clinician workflows. Therapists type during sessions and write notes after hours.",
    tried_before: "Dragon Dictate, Notion, SimplePractice — none generate SOAP-format documentation from session context.",
    tags: ["AI", "Privacy", "Clinical"],
    time_estimate: "2-4 weeks",
  },
  {
    headline: "No reliable way to verify coding ability without a live interview",
    description: "Whiteboard interviews reward stress performance, not engineering skill.",
    domain: "Dev Tools",
    difficulty: "Medium",
    context: "Algorithmic trivia tests don't reflect real work. Take-homes are too time-consuming. Live coding causes anxiety.",
    tried_before: "HackerRank, LeetCode, CodeSignal — high false-negative rates for non-traditional candidates.",
    tags: ["Hiring", "AI"],
    time_estimate: "Weekend MVP",
  },
  {
    headline: "Small farmers can't access real-time soil data — sensors cost $1,000+",
    description: "Precision farming exists only for industrial operations.",
    domain: "AgriTech",
    difficulty: "Hard",
    context: "Commercial soil sensors run $800–$2,000 per point. Lab testing has 2–3 week turnaround.",
    tried_before: "Alibaba sensor kits, university extension programs, NDVI satellite indices.",
    tags: ["Hardware", "ML"],
    time_estimate: "4-8 weeks",
  },
  {
    headline: "Freelancers in emerging markets can't build a credit history",
    description: "A developer earning $3k/month on Upwork for 5 years is invisible to lenders.",
    domain: "FinTech",
    difficulty: "Medium",
    context: "Credit scores depend on bank relationships inaccessible to 1.57B people in the gig economy.",
    tried_before: "Microfinance, M-Pesa, DeFi credit experiments too complex for mainstream.",
    tags: ["Open Banking", "Identity"],
    time_estimate: "2-3 weeks",
  },
  {
    headline: "Small business owners sign contracts they can't actually read",
    description: "A 40-page SaaS agreement is unreadable without a law degree.",
    domain: "LegalTech",
    difficulty: "Easy",
    context: "Lawyer review costs $300–$500/hour. Owners sign without reading or rely on bad summaries.",
    tried_before: "Rocket Lawyer, LegalZoom — templates only, no analysis of existing contracts.",
    tags: ["LLMs", "SMB"],
    time_estimate: "Weekend MVP",
  },
  {
    headline: "Community solar projects collapse because neighbors can't coordinate",
    description: "Group energy purchasing is 30–40% cheaper but requires consensus.",
    domain: "Climate",
    difficulty: "Hard",
    context: "Community solar participation remains below 3% of eligible households due to coordination friction.",
    tried_before: "Email chains, Facebook groups, Google Sheets — no trust or payment infrastructure.",
    tags: ["Energy", "Community"],
    time_estimate: "3-4 weeks",
  },
  {
    headline: "Live streaming is inaccessible for deaf audiences",
    description: "Auto-captions have 15–30% word error rates on technical content.",
    domain: "Accessibility",
    difficulty: "Medium",
    context: "466M people have disabling hearing loss. Auto-captions fail with accents and technical vocabulary.",
    tried_before: "CART services at $100–$200/hr, Whisper overlays with poor domain accuracy.",
    tags: ["Real-time ML", "A11y"],
    time_estimate: "2-4 weeks",
  },
  {
    headline: "Rural clinics lose patient data during power outages",
    description: "Offline-first healthcare infrastructure barely exists outside urban hospitals.",
    domain: "Infrastructure",
    difficulty: "Hard",
    context: "Clinics experience 4–12 hours of grid loss daily. Cloud EHRs become unusable.",
    tried_before: "Solar backup, OpenMRS offline silos, SMS fallback with no structured data.",
    tags: ["Offline-first", "Global Health"],
    time_estimate: "4-8 weeks",
  },
  {
    headline: "Parents can't find reliable childcare availability in real time",
    description: "Last-minute sick days leave families scrambling with phone tag across dozens of providers.",
    domain: "Health",
    difficulty: "Medium",
    context: "Childcare vacancy data is fragmented across phone calls, waitlists, and outdated websites.",
    tried_before: "Care.com listings, Facebook groups, calling 20 centers manually.",
    tags: ["Marketplace", "Families"],
    time_estimate: "2-3 weeks",
  },
  {
    headline: "Open source maintainers burn out with no sustainable funding model",
    description: "Critical infrastructure runs on volunteer labor with no revenue path.",
    domain: "Dev Tools",
    difficulty: "Medium",
    context: "80% of Fortune 100 companies depend on OSS maintained by small teams or individuals.",
    tried_before: "GitHub Sponsors, Open Collective, Tidelift — insufficient for most maintainers.",
    tags: ["OSS", "Sustainability"],
    time_estimate: "1-2 weeks",
  },
  {
    headline: "Restaurant food waste has no real-time donation routing",
    description: "Perfectly good food is thrown out while shelters are 2 miles away.",
    domain: "Climate",
    difficulty: "Easy",
    context: "US restaurants waste 22B lbs of food annually. Donation logistics are manual and unreliable.",
    tried_before: "Too Good To Go, local volunteer pickups — inconsistent coverage and no routing optimization.",
    tags: ["Logistics", "Impact"],
    time_estimate: "Weekend MVP",
  },
  {
    headline: "Immigrants can't get credentials recognized across borders",
    description: "Doctors and engineers drive Uber because their degrees aren't validated.",
    domain: "Civic Tech",
    difficulty: "Hard",
    context: "Credential recognition takes 6–18 months through opaque bureaucratic processes.",
    tried_before: "Manual document translation services, government portals with 40+ page forms.",
    tags: ["Identity", "Global"],
    time_estimate: "4-6 weeks",
  },
  {
    headline: "Students have no way to prove skills beyond a GPA",
    description: "Employers ignore transcripts that don't reflect actual project work.",
    domain: "EdTech",
    difficulty: "Easy",
    context: "Graduates list coursework but can't demonstrate applied skills in a verifiable way.",
    tried_before: "LinkedIn, portfolios on Notion, bootcamp certificates with no standardization.",
    tags: ["Credentials", "Hiring"],
    time_estimate: "Weekend MVP",
  },
  {
    headline: "Renters can't report on-time payments to build credit",
    description: "The largest monthly expense for millions isn't counted by credit bureaus.",
    domain: "FinTech",
    difficulty: "Medium",
    context: "Rent payments aren't reported unless landlords opt in to expensive third-party services.",
    tried_before: "Experian RentBureau, Piñata — limited landlord adoption and tenant awareness.",
    tags: ["Credit", "Housing"],
    time_estimate: "2-3 weeks",
  },
  {
    headline: "Elderly people fall at home with no one knowing for hours",
    description: "Medical alert devices are stigmatized and have 40% false alarm rates.",
    domain: "Health",
    difficulty: "Medium",
    context: "1 in 4 Americans 65+ fall each year. Passive monitoring without wearables is unsolved.",
    tried_before: "Life Alert pendants, Apple Watch fall detection — adoption barriers and false positives.",
    tags: ["IoT", "Aging"],
    time_estimate: "3-4 weeks",
  },
  {
    headline: "Local journalism is dying — no tool for hyperlocal news aggregation",
    description: "Neighborhood issues go unreported as city desks shrink.",
    domain: "Civic Tech",
    difficulty: "Medium",
    context: "2,900 US newspapers closed since 2005. Nextdoor is complaints, not journalism.",
    tried_before: "Patch, Substack, citizen reporting apps with no editorial workflow.",
    tags: ["Media", "Community"],
    time_estimate: "2-4 weeks",
  },
  {
    headline: "API documentation is always out of date with the actual code",
    description: "Developers waste hours when docs drift from implementation.",
    domain: "Dev Tools",
    difficulty: "Easy",
    context: "Docs are written once and abandoned. API changes ship without doc updates.",
    tried_before: "Swagger auto-gen, ReadMe, Mintlify — still require manual curation.",
    tags: ["Developer Experience", "AI"],
    time_estimate: "Weekend MVP",
  },
  {
    headline: "Small landlords manage properties on spreadsheets and text messages",
    description: "Maintenance requests, rent collection, and leases live in chaos.",
    domain: "Housing",
    difficulty: "Easy",
    context: "48M Americans rent from small landlords who can't afford enterprise property software.",
    tried_before: "Buildium, AppFolio — priced for 50+ unit portfolios, overkill for 2–4 units.",
    tags: ["PropTech", "SMB"],
    time_estimate: "1-2 weeks",
  },
  {
    headline: "Carbon footprint of purchases is invisible at checkout",
    description: "Consumers want to buy sustainably but have zero data at point of sale.",
    domain: "Climate",
    difficulty: "Medium",
    context: "Product-level emissions data exists in LCA databases but isn't consumer-facing.",
    tried_before: "Carbon labeling pilots, browser extensions scraping product pages manually.",
    tags: ["Climate", "Consumer"],
    time_estimate: "2-3 weeks",
  },
  {
    headline: "PhD researchers spend 30% of time on grant administration",
    description: "Applying for funding is a full-time job disguised as side work.",
    domain: "EdTech",
    difficulty: "Hard",
    context: "Grant applications are bespoke PDFs with overlapping requirements across agencies.",
    tried_before: "GrantForward search, university research offices — no application automation.",
    tags: ["Research", "Automation"],
    time_estimate: "4-6 weeks",
  },
  {
    headline: "Warehouse workers have no visibility into their schedule until the day of",
    description: "Unpredictable shifts destroy childcare and second-job planning.",
    domain: "Accessibility",
    difficulty: "Medium",
    context: "Just-in-time scheduling algorithms optimize for employers, not worker stability.",
    tried_before: "When I Work, Deputy — built for managers, not worker advocacy.",
    tags: ["Labor", "Scheduling"],
    time_estimate: "2-3 weeks",
  },
  {
    headline: "Indie game developers can't find playtesters who match their target audience",
    description: "Feedback comes from other devs, not actual players.",
    domain: "Dev Tools",
    difficulty: "Easy",
    context: "Playtesting recruitment is Discord posts and hoping friends are honest.",
    tried_before: "PlaytestCloud, Reddit posts — expensive or wrong audience demographics.",
    tags: ["Gaming", "Community"],
    time_estimate: "Weekend MVP",
  },
  {
    headline: "Medication interactions aren't checked across doctors and pharmacies",
    description: "Patients on 5+ meds have no unified interaction view.",
    domain: "Health",
    difficulty: "Hard",
    context: "Each provider sees their slice. Pharmacy systems don't talk to hospital EHRs.",
    tried_before: "Medisafe app, pharmacist consultations — patient-managed and error-prone.",
    tags: ["Health", "Data"],
    time_estimate: "4-8 weeks",
  },
  {
    headline: "Refugees lose proof of work history when fleeing conflict",
    description: "Professional portfolios and references vanish overnight.",
    domain: "Civic Tech",
    difficulty: "Medium",
    context: "36M refugees worldwide can't prove qualifications to employers in host countries.",
    tried_before: "LinkedIn profiles, paper certificates — lost or untranslatable.",
    tags: ["Identity", "Global"],
    time_estimate: "3-4 weeks",
  },
  {
    headline: "Podcast discovery is broken beyond the top 100 shows",
    description: "Niche shows with perfect audience fit are impossible to find.",
    domain: "Dev Tools",
    difficulty: "Easy",
    context: "Spotify and Apple optimize for engagement, not topic relevance to your interests.",
    tried_before: "Podcast apps with genre tags, Twitter recommendations — no semantic matching.",
    tags: ["Audio", "Discovery"],
    time_estimate: "1-2 weeks",
  },
  {
    headline: "Electric vehicle owners can't find reliable public charging availability",
    description: "Apps show chargers that are broken, occupied, or don't exist.",
    domain: "Climate",
    difficulty: "Medium",
    context: "Range anxiety is really data anxiety — charger status is stale or wrong.",
    tried_before: "PlugShare, ChargePoint app — crowdsourced data with no real-time verification.",
    tags: ["EV", "Maps"],
    time_estimate: "2-4 weeks",
  },
  {
    headline: "Nonprofits can't measure program impact without hiring data scientists",
    description: "Funders demand metrics that small orgs can't produce.",
    domain: "Civic Tech",
    difficulty: "Medium",
    context: "Impact reporting requires SQL, survey design, and statistical literacy most NGOs lack.",
    tried_before: "Salesforce NPSP, Excel — manual and not designed for outcome measurement.",
    tags: ["Nonprofit", "Analytics"],
    time_estimate: "3-4 weeks",
  },
  {
    headline: "Language learners have no one to practice with at their exact level",
    description: "Tutors cost $30/hr and apps don't simulate real conversation.",
    domain: "EdTech",
    difficulty: "Easy",
    context: "Duolingo teaches vocabulary but conversation practice requires expensive human tutors.",
    tried_before: "iTalki, HelloTalk — matching friction and inconsistent partner quality.",
    tags: ["AI", "Language"],
    time_estimate: "Weekend MVP",
  },
  {
    headline: "Homeowners don't know if their solar panels are underperforming",
    description: "Install-and-forget means degraded output goes unnoticed for years.",
    domain: "Climate",
    difficulty: "Medium",
    context: "Most residential solar owners check production once a year at best.",
    tried_before: "Enphase app, utility bills — no benchmarking against expected output or neighbors.",
    tags: ["Energy", "IoT"],
    time_estimate: "2-3 weeks",
  },
  {
    headline: "Street vendors operate entirely in cash with no path to formal credit",
    description: "Successful food cart operators can't get a business loan.",
    domain: "FinTech",
    difficulty: "Medium",
    context: "Informal economy workers have revenue but no paper trail banks accept.",
    tried_before: "Square, Venmo — payment rails without credit-building infrastructure.",
    tags: ["SMB", "Emerging Markets"],
    time_estimate: "2-4 weeks",
  },
  {
    headline: "Clinical trial recruitment takes longer than the trial itself",
    description: "85% of trials fail to enroll on time, delaying life-saving treatments.",
    domain: "Health",
    difficulty: "Hard",
    context: "Patient matching is manual — coordinators search EHRs by hand for eligible participants.",
    tried_before: "ClinicalTrials.gov, patient advocacy groups — no automated eligibility matching.",
    tags: ["Health", "AI"],
    time_estimate: "4-8 weeks",
  },
  {
    headline: "Remote teams lose institutional knowledge when people leave",
    description: "Tribal knowledge walks out the door with no capture system.",
    domain: "Dev Tools",
    difficulty: "Medium",
    context: "Slack history is unsearchable chaos. Wikis are stale the day they're written.",
    tried_before: "Notion, Confluence, Guru — require manual maintenance nobody does.",
    tags: ["Knowledge", "Remote"],
    time_estimate: "2-3 weeks",
  },
  {
    headline: "Disabled travelers can't verify if hotels are actually accessible",
    description: "'Accessible' on Booking.com means wildly different things.",
    domain: "Accessibility",
    difficulty: "Medium",
    context: "Wheelchair users arrive to find 'accessible' rooms with bathroom doors too narrow.",
    tried_before: "TripAdvisor reviews, calling hotels — inconsistent and unreliable information.",
    tags: ["Travel", "A11y"],
    time_estimate: "2-4 weeks",
  },
  {
    headline: "Music teachers can't track student practice between lessons",
    description: "Weekly lessons undo when students don't practice with correct technique.",
    domain: "EdTech",
    difficulty: "Easy",
    context: "Teachers assign exercises but have no visibility until the next session.",
    tried_before: "Practice journals, generic metronome apps — no progress tracking or feedback.",
    tags: ["Music", "EdTech"],
    time_estimate: "1-2 weeks",
  },
  {
    headline: "Scam calls target elderly people with no effective blocking at landline level",
    description: "Robocall filters don't work on legacy phone systems.",
    domain: "Accessibility",
    difficulty: "Medium",
    context: "Seniors lose $3B annually to phone scams. Carrier-level blocking is inconsistent.",
    tried_before: "Nomorobo, Hiya — mobile-focused, landline gaps, false positives block doctors.",
    tags: ["Security", "Aging"],
    time_estimate: "2-3 weeks",
  },
  {
    headline: "Freelance designers can't enforce payment after delivering work",
    description: "Clients ghost after receiving final files.",
    domain: "FinTech",
    difficulty: "Easy",
    context: "Creative freelancers have no escrow mechanism suited to design deliverables.",
    tried_before: "Upwork escrow, PayPal invoices — high fees or no file-release mechanism.",
    tags: ["Freelance", "Payments"],
    time_estimate: "Weekend MVP",
  },
  {
    headline: "Urban gardeners don't know what's safe to plant in contaminated soil",
    description: "Community gardens sit on former industrial sites with unknown toxicity.",
    domain: "AgriTech",
    difficulty: "Hard",
    context: "Soil testing costs $200+ per sample. Urban gardeners plant blind in potentially toxic earth.",
    tried_before: "EPA databases, university extension — not localized or actionable for plot-level decisions.",
    tags: ["Urban", "Health"],
    time_estimate: "3-4 weeks",
  },
  {
    headline: "New parents can't find pediatricians accepting patients",
    description: "Waitlists are 6+ months in most metro areas.",
    domain: "Health",
    difficulty: "Easy",
    context: "Pediatrician availability isn't published anywhere. Parents call 30+ offices.",
    tried_before: "Zocdoc, insurance directories — outdated availability data.",
    tags: ["Health", "Marketplace"],
    time_estimate: "1-2 weeks",
  },
  {
    headline: "DevOps on-call rotations burn out engineers with alert fatigue",
    description: "PagerDuty pages for non-critical alerts at 3am destroy teams.",
    domain: "Dev Tools",
    difficulty: "Medium",
    context: "Alert rules proliferate unchecked. 90% of pages don't require human action.",
    tried_before: "PagerDuty, Opsgenie — paging infrastructure, not alert intelligence.",
    tags: ["DevOps", "AI"],
    time_estimate: "2-3 weeks",
  },
  {
    headline: "Tenants can't document maintenance issues with legal weight",
    description: "Landlords ignore texts about mold until lease renewal.",
    domain: "Housing",
    difficulty: "Easy",
    context: "Maintenance requests via text have no timestamp, photo evidence, or legal trail.",
    tried_before: "Email, tenant union hotlines — no standardized evidence collection.",
    tags: ["Legal", "PropTech"],
    time_estimate: "Weekend MVP",
  },
  {
    headline: "Small museums can't digitize collections on a budget",
    description: "Archives sit in boxes because digitization vendors charge $50+ per item.",
    domain: "EdTech",
    difficulty: "Medium",
    context: "35,000 museums in the US, most with undigitized collections inaccessible to researchers.",
    tried_before: "Google Arts & Culture partnerships, expensive scanning services.",
    tags: ["Culture", "AI"],
    time_estimate: "3-4 weeks",
  },
  {
    headline: "Gig delivery drivers can't optimize routes across multiple apps",
    description: "Switching between DoorDash, Uber Eats, and Instacart kills earnings.",
    domain: "FinTech",
    difficulty: "Medium",
    context: "Drivers juggle 3 apps with conflicting routes and no unified earnings view.",
    tried_before: "Stride, Everlance — mileage tracking only, no multi-app route optimization.",
    tags: ["Gig Economy", "Logistics"],
    time_estimate: "2-4 weeks",
  },
  {
    headline: "People with ADHD can't find tools built for how their brain works",
    description: "Productivity apps assume neurotypical executive function.",
    domain: "Mental Health",
    difficulty: "Medium",
    context: "Todo apps become guilt machines. Time blindness makes calendar apps useless.",
    tried_before: "Todoist, Forest, body doubling apps — not designed for ADHD cognition patterns.",
    tags: ["Neurodiversity", "Productivity"],
    time_estimate: "2-3 weeks",
  },
  {
    headline: "Local businesses can't compete with Amazon on delivery speed",
    description: "Same-day local delivery infrastructure doesn't exist for independents.",
    domain: "FinTech",
    difficulty: "Hard",
    context: "Buy-local movements fail when Amazon delivers in 2 hours and the shop takes 3 days.",
    tried_before: "Shopify local delivery, Instacart — built for chains, not single-location shops.",
    tags: ["Retail", "Logistics"],
    time_estimate: "4-6 weeks",
  },
  {
    headline: "Scientists can't reproduce published results — methods sections are incomplete",
    description: "The replication crisis stems from under-specified protocols.",
    domain: "EdTech",
    difficulty: "Hard",
    context: "70% of researchers failed to reproduce another scientist's experiments.",
    tried_before: "Protocols.io, open data mandates — low adoption and incomplete parameter capture.",
    tags: ["Research", "Open Science"],
    time_estimate: "4-8 weeks",
  },
  {
    headline: "Pet owners can't find emergency vet care after hours",
    description: "Google Maps shows closed clinics during pet emergencies at midnight.",
    domain: "Health",
    difficulty: "Easy",
    context: "Emergency vet availability changes nightly. Owners drive to closed clinics in panic.",
    tried_before: "Google Maps, ASPCA hotline — no real-time open/closed status for emergency vets.",
    tags: ["Pets", "Health"],
    time_estimate: "Weekend MVP",
  },
  {
    headline: "Code review bottlenecks block entire teams waiting on one senior engineer",
    description: "PRs sit for days because review capacity doesn't scale.",
    domain: "Dev Tools",
    difficulty: "Easy",
    context: "Senior engineers become review bottlenecks. Junior PRs queue for days.",
    tried_before: "GitHub review assignments, LinearB metrics — measure the problem, don't solve it.",
    tags: ["Developer Experience", "AI"],
    time_estimate: "1-2 weeks",
  },
  {
    headline: "Flood risk maps are outdated — homeowners buy properties blind",
    description: "FEMA maps lag years behind actual climate risk.",
    domain: "Climate",
    difficulty: "Hard",
    context: "14.6M properties at flood risk aren't in FEMA flood zones. Insurance and buyers rely on stale data.",
    tried_before: "FEMA NFHL, First Street Foundation — better data exists but isn't at point of purchase.",
    tags: ["Climate", "PropTech"],
    time_estimate: "4-6 weeks",
  },
  {
    headline: "Caregivers of dementia patients have no respite coordination",
    description: "Family caregivers average 24 hours/week with no backup system.",
    domain: "Mental Health",
    difficulty: "Medium",
    context: "40M Americans are unpaid caregivers. Respite care booking is fragmented and expensive.",
    tried_before: "Care.com, local agencies — not designed for dementia-specific needs or family coordination.",
    tags: ["Aging", "Health"],
    time_estimate: "3-4 weeks",
  },
  {
    headline: "Startup founders can't find compatible co-founders with complementary skills",
    description: "YC co-founder matching is a lottery. Most founders go solo too long.",
    domain: "Dev Tools",
    difficulty: "Easy",
    context: "Co-founder divorce is the #1 startup killer. Matching is Twitter DMs and luck.",
    tried_before: "YC Co-Founder Matching, CoFoundersLab — low signal-to-noise ratio.",
    tags: ["Startups", "Matching"],
    time_estimate: "Weekend MVP",
  },
];

const VARIATIONS = [
  (h: string) => h,
  (h: string) => h.replace("can't", "cannot"),
  (h: string) => `${h.split("—")[0].trim()} — and it's getting worse`,
  (h: string) => h.replace(/^(\w)/, (m) => m.toUpperCase()),
];

const SOURCES: Source[] = ["reddit", "hn"];
const SUBREDDITS = ["SomebodyMakeThis", "startups", "Entrepreneur", "SideProject", "ideas"];

function hash(n: number): number {
  return ((n * 2654435761) >>> 0) % 1000;
}

export function generateSeedProblems(count = 100): Problem[] {
  const now = Date.now();
  const problems: Problem[] = [];

  for (let i = 0; i < count; i++) {
    const template = TEMPLATES[i % TEMPLATES.length];
    const variation = VARIATIONS[Math.floor(i / TEMPLATES.length) % VARIATIONS.length];
    const headline = variation(template.headline);
    const source = SOURCES[i % 2];
    const h = hash(i);

    const hoursAgo = (i * 0.23) % 24;

    problems.push({
      id: `seed-${i + 1}`,
      headline,
      description: template.description,
      domain: template.domain,
      difficulty: template.difficulty,
      context: template.context,
      tried_before: template.tried_before,
      builders_count: 200 + (h % 4800),
      builders_started_pct: 5 + (h % 45),
      source,
      source_url:
        source === "reddit"
          ? `https://reddit.com/r/${SUBREDDITS[i % SUBREDDITS.length]}/comments/seed${i + 1}`
          : `https://news.ycombinator.com/item?id=seed${10000 + i}`,
      raw_post: `[${source === "reddit" ? "Reddit" : "Ask HN"}] ${headline}\n\n${template.description}\n\nSomeone please build this.`,
      time_estimate: template.time_estimate,
      tags: template.tags,
      cover_image: COVER_IMAGES[i],
      created_at: new Date(now - hoursAgo * 60 * 60 * 1000).toISOString(),
    });
  }

  return problems.sort(
    (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
  );
}

export const SEED_PROBLEMS = generateSeedProblems(100);
